services:
  postgres:
    image: postgres:17-alpine
    container_name: shortin-postgres
    environment:
      POSTGRES_USER: shortin
      POSTGRES_PASSWORD: shortin
      POSTGRES_DB: shortin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shortin"]
      interval: 5s
      timeout: 5s
      retries: 5
  kafka:
    image: apache/kafka:4.0.0
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-cluster.sh cluster-id -b localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
