version: '3.8'

services:
  postgres:
    image: postgres:16  # Latest stable version as of now
    container_name: shortin-postgres
    environment:
      POSTGRES_USER: shortin
      POSTGRES_PASSWORD: shortin
      POSTGRES_DB: shortin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shortin"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
