name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  REGISTRY: ghcr.io

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/actions/setup-gradle@v4

      - name: Lint & Static Analysis
        run: ./gradlew ktlintCheck detekt --no-daemon

      - name: Unit Tests
        run: ./gradlew test --no-daemon

      - name: Integration Tests
        run: ./gradlew integrationTest --no-daemon

  build-docker:
    runs-on: ubuntu-latest
    needs: check
    permissions:
      contents: read
      packages: write

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/actions/setup-gradle@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          ./gradlew --no-daemon jib \
          -Djib.to.image=${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }} \
          -Djib.to.auth.username=${{ github.actor }} \
          -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
